import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from '@next/font/google';
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from '@/app/theme-context';
import HeaderOffers from "@/components/head-offers";
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Choose weights as per your requirement
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[#FFF6F4] dark:bg-black max-w-[1300px] w-full mx-auto  text-black dark:text-white `}
        suppressHydrationWarning={true}
      >
        <ThemeProvider>
          <HeaderOffers />
          <Navbar />
          {/* <div className="container mx-auto"> */}
          <div className="bg-[#FFF6F4] dark:bg-black">
            {children}

          </div>
          <Footer />
          {/* </div> */}
        </ThemeProvider>

      </body>
    </html>
  );
}
